default_stages:
  - pre-commit
fail_fast: false
minimum_pre_commit_version: "2.17.0"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^(?!(ui)/).*\.(js|jsx|json|css|less|scss|ts|tsx|graphql|md|markdown)$

  - repo: local
    hooks:
      - id: validate-commit-msg
        name: Validate Commit Message
        language: system
        entry: python local_pre_commit_hooks/validate_commit_message.py
        args: [.git/COMMIT_EDITMSG]
        stages:
          - commit-msg
        always_run: true
        verbose: true

  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort

ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
