services:
  postgres:
    container_name: snowflake_to_postgres_db
    image: postgres:16
    shm_size: 128mb
    ports:
      - "5547:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      snowflake-postgres-net:
        ipv4_address: 172.14.111.11

networks:
  snowflake-postgres-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.14.111.0/24
